SELECT        PERSONA.NOMBRE, PERSONA.APELLIDO
FROM            CLIENTE INNER JOIN
                         PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA

SELECT        PROVEEDOR.NOMBRE, INGRESO.TOTAL
FROM            PROVEEDOR INNER JOIN
                         INGRESO ON PROVEEDOR.IDPROVEEDOR = INGRESO.IDPROVEEDOR

SELECT MARCA.NOMBRE AS Marca, SUM(DETALLEVENTA.CANTIDAD) AS CantidadTotal
FROM MARCA
INNER JOIN PRODUCTO ON MARCA.IDMARCA = PRODUCTO.IDMARCA
INNER JOIN DETALLEVENTA ON PRODUCTO.IDPRODUCTO = DETALLEVENTA.IDPRODUCTO
GROUP BY MARCA.NOMBRE
ORDER BY SUM(DETALLEVENTA.CANTIDAD) DESC;

SELECT SUM(UNIDAD) AS TOTAL
FROM PRODUCTO;

SELECT PRODUCTO.NOMBRE AS NOMBRE, DETALLEING.FECHAVENC
FROM DETALLEING
INNER JOIN PRODUCTO ON DETALLEING.IDPRODUCTO = PRODUCTO.IDPRODUCTO
WHERE DETALLEING.FECHAVENC BETWEEN GETDATE() AND DATEADD(day, 30, GETDATE());

SELECT U.NOMBREUSER AS VENDEDOR, COUNT(DV.IDPRODUCTO) AS CANTIDAD
FROM USUARIO U
JOIN VENTA V ON U.IDUSUARIO = V.IDVENDEDOR
JOIN DETALLEVENTA DV ON V.IDVENTA = DV.IDVENTA
GROUP BY U.NOMBREUSER;

SELECT P.NOMBRE, P.APELLIDO, SUM(V.TOTAL) AS TOTAL
FROM CLIENTE C
JOIN PERSONA P ON C.IDPERSONA = P.IDPERSONA
JOIN VENTA V ON C.IDCLIENTE = V.IDCLIENTE
GROUP BY P.NOMBRE, P.APELLIDO;

SELECT TP.NOMBRE AS TIPOPRODUCTO, SUM(DV.CANTIDAD) AS CANTIDAD
FROM TIPOPROD TP
JOIN PRODUCTO P ON TP.IDTIPOPROD = P.IDTIPOPROD
JOIN DETALLEVENTA DV ON P.IDPRODUCTO = DV.IDPRODUCTO
GROUP BY TP.NOMBRE;

SELECT P.NOMBRE, P.APELLIDO, SUM(V.TOTAL) AS TOTAL
FROM CLIENTE C
JOIN PERSONA P ON C.IDPERSONA = P.IDPERSONA
JOIN VENTA V ON C.IDCLIENTE = V.IDCLIENTE
GROUP BY P.NOMBRE, P.APELLIDO
HAVING SUM(V.TOTAL) > 50;

SELECT PR.NOMBRE PROVEEDOR, COUNT(P.IDPROVEE) PRODUCTOS_SUMINISTRADOS
FROM PROVEEDOR PR
INNER JOIN PROVEE P ON PR.IDPROVEEDOR = P.IDPROVEEDOR
GROUP BY PR.NOMBRE
ORDER BY COUNT(P.IDPROVEE) DESC;





